"""token_cards.py — Non-collectible token card database.

Tokens are cards generated by other cards (deathrattles, battlecries, triggers).
They are NOT in unified_standard.json because they are non-collectible.
This module provides their data for simulation purposes.
"""
from __future__ import annotations

_TOKEN_DB = {
    "CATA_527t2": {
        "cardId": "CATA_527t2",
        "dbfId": 122774,
        "name": "奈瑟匹拉，脱困古灵",
        "ename": "Nespirah, Freed",
        "cost": 3,
        "attack": 3,
        "health": 5,
        "type": "MINION",
        "cardClass": "DEMONHUNTER",
        "race": "NAGA",
        "rarity": "FREE",
        "text": "每当你施放一个法术，将一张随机娜迦随从牌置入你的手牌。",
        "englishText": "Whenever you cast a spell, add a random Naga minion to your hand.",
        "mechanics": ["TRIGGER_VISUAL"],
        "trigger_type": "ON_SPELL_CAST",
        "trigger_effect": "ADD_RANDOM_NAGA",
    },
}

_NAGA_POOL = [
    {"name": "凶恶的滑矛纳迦", "cost": 1, "attack": 1, "health": 3},
    {"name": "女祭司瓦丽丝琪", "cost": 1, "attack": 1, "health": 1},
    {"name": "滑矛布袋手偶", "cost": 1, "attack": 1, "health": 2},
    {"name": "墨晕伏击者", "cost": 2, "attack": 1, "health": 2},
    {"name": "女王护卫", "cost": 2, "attack": 2, "health": 3},
    {"name": "干鳞警官", "cost": 2, "attack": 2, "health": 2},
    {"name": "暗水记录员", "cost": 2, "attack": 3, "health": 2},
    {"name": "游荡贤者", "cost": 2, "attack": 2, "health": 2},
    {"name": "焦渴的亡命徒", "cost": 2, "attack": 3, "health": 2},
    {"name": "虹彩闪鳞纳迦", "cost": 2, "attack": 2, "health": 3},
    {"name": "怒鳞纳迦", "cost": 3, "attack": 3, "health": 3},
    {"name": "盲眼神射手", "cost": 3, "attack": 1, "health": 3},
    {"name": "蛇眼", "cost": 3, "attack": 2, "health": 4},
    {"name": "赛丝诺女士", "cost": 3, "attack": 1, "health": 4},
    {"name": "重钳执行者", "cost": 3, "attack": 3, "health": 4},
    {"name": "恶念变异体", "cost": 3, "attack": 3, "health": 4},
    {"name": "装甲放血纳迦", "cost": 3, "attack": 3, "health": 1},
    {"name": "双弓积骇纳迦", "cost": 4, "attack": 4, "health": 4},
    {"name": "学校教师", "cost": 4, "attack": 5, "health": 4},
    {"name": "巫婆纳迦", "cost": 4, "attack": 4, "health": 4},
    {"name": "贪婪的邪能钓鱼者", "cost": 6, "attack": 5, "health": 5},
    {"name": "库斯克指挥官", "cost": 6, "attack": 3, "health": 7},
    {"name": "艾萨拉，海洋之主", "cost": 8, "attack": 8, "health": 8},
]


def get_token(card_id: str) -> dict | None:
    return _TOKEN_DB.get(card_id)


def get_random_naga() -> dict:
    """Return a random Naga minion data for token generation."""
    import random
    return random.choice(_NAGA_POOL)


def create_naga_card(naga_data: dict) -> object:
    """Create a Card-like object from naga data for hand insertion."""
    from analysis.models.card import Card
    return Card(
        card_id="TOKEN_NAGA",
        name=naga_data.get("name", "Naga"),
        cost=naga_data.get("cost", 2),
        original_cost=naga_data.get("cost", 2),
        card_type="MINION",
        attack=naga_data.get("attack", 1),
        health=naga_data.get("health", 1),
        race="NAGA",
    )
